### ISSUE TITLE
First time installation fails with missing file - general.config

### ISSUE THREAD

**Issue by tgmerritt** [Apollys/PoEDynamicLootFilter#9]
PS C:\Users\tgmer\Downloads\PoEDynamicLootFilter> python .\setup.py
Welcome to the first-time setup script for PoE DLF!

Step 1: Checking python version...
Python version 3 detected, success!

Step 2: Set GUI toggle hotkey

Hotkey syntax: Ctrl = "^", Shift = "+", Alt = "!"
Example: Ctrl-Shift-a = "^+a"
Function keys may be typed as "F1" or "f1", ...
Enter GUI toggle hotkey (leave blank for default: "F8"):

GUI toggle hotkey has been set to "F8"
To change the hotkey later, either scroll to the bottom of dynamic_loot_filter.ahk
or re-run this script, and use Ctrl-C to exit after this step.

Step 3: Create your profile
Enter new profile name: DLF
Traceback (most recent call last):
  File "C:\Users\tgmer\Downloads\PoEDynamicLootFilter\setup.py", line 119, in <module>
    main()
  File "C:\Users\tgmer\Downloads\PoEDynamicLootFilter\setup.py", line 74, in main
    if (new_profile_name in profile.GetAllProfileNames()):
  File "C:\Users\tgmer\Downloads\PoEDynamicLootFilter\profile.py", line 273, in GetAllProfileNames
    active_profile_name = GetActiveProfileName()
  File "C:\Users\tgmer\Downloads\PoEDynamicLootFilter\profile.py", line 244, in GetActiveProfileName
    raise RuntimeError('General config: "{}" does not exist'.format(kGeneralConfigFullpath))
RuntimeError: General config: "Profiles\general.config" does not exist

**Comment by Apollys** [comment]
This should be fixed now.
